// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTTJeOLsE2sWTn1ee7DA7R3LJ5NZm-tH4',
    appId: '1:853319133868:android:478b813fc3b02c4c738d09',
    messagingSenderId: '853319133868',
    projectId: 'doan2-a4abf',
    databaseURL: 'https://doan2-a4abf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'doan2-a4abf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK9o1ET_Vk-GjGJRfaoz48hYMBE2wDC9Y',
    appId: '1:853319133868:ios:d76f28c2f9b2047f738d09',
    messagingSenderId: '853319133868',
    projectId: 'doan2-a4abf',
    databaseURL: 'https://doan2-a4abf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'doan2-a4abf.appspot.com',
    iosClientId: '853319133868-pq1ncpn9ih0pduho084f4onihgff8mqm.apps.googleusercontent.com',
    iosBundleId: 'com.example.baseproject',
  );
}
