// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_RSsIMCgJD3JIcXlu2DaCaJEVjtw1SPo',
    appId: '1:924366898855:android:52d276c2cec7f72b217d82',
    messagingSenderId: '924366898855',
    projectId: 'loginanggandfb',
    databaseURL: 'https://loginanggandfb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'loginanggandfb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwFVg1aWwKtwlzKZQ2FWvCCBO7PrvHOyY',
    appId: '1:924366898855:ios:4547199952a23e8e217d82',
    messagingSenderId: '924366898855',
    projectId: 'loginanggandfb',
    databaseURL: 'https://loginanggandfb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'loginanggandfb.appspot.com',
    androidClientId: '924366898855-msbfvafsqpsudmia3jdocldq0rkiepck.apps.googleusercontent.com',
    iosClientId: '924366898855-sbdcb07dcbgpl3e9aa6j3j78tkl4osgd.apps.googleusercontent.com',
    iosBundleId: 'com.example.baseproject',
  );
}
